### ISSUE TITLE
Hyperlink for FAQ is incorrect in 'IBM classic bare metal to bare metal migration overview'

### ISSUE THREAD

**Issue by rahulippar** [ibm-cloud-docs/cloud-infrastructure#9] opened 2021-09-06 17:40 UTC
Document link - [IBM classic bare metal to bare metal migration overview](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-p-p-migration-bare-metal-overview)

Issue : In 'Help' section 

- Hyperlink for 'FAQS for bare metal to bare metal' is incorrect, its still pointing to test environment
- Numbering is incorrect for help items
<img width="1762" alt="Screen Shot 2021-09-06 at 11 08 08 PM" src="https://user-images.githubusercontent.com/30128437/132249735-2af3cfd0-f87d-4d0c-af22-cdf1f9cb2d2d.png">
<img width="1687" alt="Screen Shot 2021-09-06 at 11 04 48 PM" src="https://user-images.githubusercontent.com/30128437/132249750-c0e4c0d4-0a11-45cd-8729-f1ea03c6b2da.png">

**Comment by gudrun-wolfgram** [comment] 2021-09-07 14:03
Not able to reproduce this issue. Closing.

**Closed by gudrun-wolfgram** 2021-09-07 14:03 UTC

**Comment by Nicholas-Pierotti** [comment] 2021-09-07 14:28
I have made the fixes.
